### ISSUE TITLE
hiderightclick not working

### ISSUE THREAD

**Issue by caralmar** [dceejay/RedMap#69]
I have implemented a map with markers.  I set the "hiderightclick" to "true".  If I right-click on the map, nothing happens.  However, if I right-click on a marker, I get a "Delete" button.  I don't want the user to have the ability to delete markers... thanks!

Right-click on a marker:
![image](https://user-images.githubusercontent.com/26122325/53048154-1e38f780-3462-11e9-8eca-f8927c6f89fb.png)

Code to move map:
![image](https://user-images.githubusercontent.com/26122325/53048189-2f820400-3462-11e9-9a02-a0b5daa6c30a.png)

Thanks!

**Comment by dceejay** [comment]
good spot - will fix

**Comment by dceejay** [comment]
fix pushed as version 1.5.24

**Comment by caralmar** [comment]
Hi, I've updated my NodeRED node to 1.5.24 and still have the right-click issue:
![image](https://user-images.githubusercontent.com/26122325/53182985-86a1e900-35c8-11e9-8f32-08b4c15eb399.png)

**Comment by caralmar** [comment]
The popup doesn't have the close either.
![image](https://user-images.githubusercontent.com/26122325/53183797-fd8bb180-35c9-11e9-9f39-c9fcda4f7970.png)

**Comment by dceejay** [comment]
Have you refreshed your browser cache properly by ctrl-R a few times ?

**Comment by caralmar** [comment]
Hi, ok, I tried this in incognito and it still wasn't working.  I then cleared the Chrome cache and it started working... sorry about that!  And thanks again!
